# Generated by Django 2.2 on 2019-04-25 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=80)),
                ('lastName', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('message', models.CharField(blank=True, max_length=800, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attending', models.BooleanField(default=False)),
                ('lodging', models.CharField(blank=True, max_length=56, null=True)),
                ('numInviteesAlotted', models.IntegerField(blank=True, null=True)),
                ('numAdults', models.IntegerField(blank=True, null=True)),
                ('numChildren', models.IntegerField(blank=True, null=True)),
                ('arrivalDay', models.CharField(blank=True, max_length=10)),
                ('departureDay', models.CharField(blank=True, max_length=10, null=True)),
                ('volunteeringToHelp', models.BooleanField(blank=True, default=False)),
                ('numVeg', models.IntegerField(blank=True, null=True)),
                ('numNoDairy', models.IntegerField(blank=True, null=True)),
                ('numNoGluten', models.IntegerField(blank=True, null=True)),
                ('additionalNotes', models.CharField(blank=True, max_length=600, null=True)),
                ('needTent', models.BooleanField(default=False)),
                ('needPad', models.BooleanField(default=False)),
                ('needSleepingBag', models.BooleanField(default=False)),
                ('submitted', models.BooleanField(default=False)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=28, null=True)),
                ('lastName', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('mobileNumber', models.CharField(blank=True, max_length=14, null=True)),
                ('zipCode', models.CharField(blank=True, max_length=10, null=True)),
                ('rsvpSubmitted', models.BooleanField(blank=True, default=False)),
                ('rsvp', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='wedding.Rsvp')),
            ],
        ),
    ]
